// 按需全局引入 vant组件
import Vue from 'vue'
import { Button,Area,Tab,Empty ,Form,Sticky,Loading , Tabs,Rate,Uploader ,Calendar ,AddressList  ,SwipeCell ,Sidebar, SidebarItem,TreeSelect ,Switch ,ContactEdit ,ContactList ,ContactCard ,Field,RadioGroup, Radio , Checkbox, CheckboxGroup,Popup,Stepper,Tag,SubmitBar,CellGroup, Card,List,Sku,Divider,ActionSheet, GoodsAction, GoodsActionIcon, GoodsActionButton,CouponCell, CouponList,Cell,NavBar, Tabbar, TabbarItem ,Lazyload ,Search , Swipe, SwipeItem ,Toast,Grid, GridItem,Image as VanImage ,Skeleton,Col, Row,CountDown,Icon} from 'vant'
Vue.use(Button)
Vue.use(Cell)
Vue.use(List)
Vue.use(Lazyload)
Vue.use(Search)
Vue.use(SwipeItem)
Vue.use(Swipe)
Vue.use(Toast)
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(VanImage);
Vue.use(Skeleton);
Vue.use(Empty);
Vue.use(Sticky);
Vue.use(SwipeCell);
Vue.use(Uploader);
Vue.use(Rate);
Vue.use(Col);
Vue.use(Row);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Form);
Vue.use(Icon);
Vue.use(Calendar);
Vue.use(ContactEdit);
Vue.use(CountDown);
Vue.use(Area);
Vue.use(AddressList)
Vue.use(TreeSelect);
Vue.use(Divider);
Vue.use(NavBar);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(ContactCard);
Vue.use(CouponCell);
Vue.use(Switch);
Vue.use(CouponList);
Vue.use(ActionSheet);
Vue.use(ContactList);
Vue.use(Popup);
Vue.use(Sku);
Vue.use(SubmitBar);
Vue.use(Stepper);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(CellGroup);
Vue.use(GoodsActionIcon);
Vue.use(Card);
Vue.use(Tag);
Vue.use(Checkbox);
Vue.use(Field);
Vue.use(CheckboxGroup);
Vue.use(Tabbar).use(TabbarItem)

Vue.use(Loading);
//全局返回
Vue.prototype.$backPage = ()=>{
    window.history.back()
}